-- Your SQL goes here
CREATE TABLE IF NOT EXISTS directories (
    id TEXT NOT NULL PRIMARY KEY,
    path TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);